### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by juliettecougnoux** [Evolix/chexpire#43]

**Comment by munadikiehl** [comment]
Dear Madam
Hello, I'm graphic designer and wanted to help you with the logo. Do you have any requirements for the logo? 

Best Regard,
Munadi Kiehl

**Comment by juliettecougnoux** [comment]
Hi Munadi!

First of all thank you for your interest in the chexpire project.

For the logo I don't have any requirements, only I already started to create one, but I'm not a graphic designer so you are very welcome to help.

To see what I did:
[](http://jcougnoux.perso.evolix.net/images/chexpirev4.png)
[](http://jcougnoux.perso.evolix.net/images/chexpirev9.png)
[](http://jcougnoux.perso.evolix.net/images/chexpirev10.png)

You can tell me what you think about it, use it (I can give you the sources), or create something completely different because as I said before, that's not what I usually do.

Thank you again!

**Comment by jlecour** [comment]
https://github.com/Evolix/chexpire/blob/master/app/assets/images/chexpire10.png
